# Generated by Django 3.1.2 on 2021-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='venue',
            field=models.CharField(choices=[('S', 'SECC'), ('B', 'Barrowland Ballroom'), ('H', 'Hydro')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
