# Generated by Django 3.1.2 on 2021-01-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_date'),
    ]

    operations = [
    ]
