# Generated by Django 3.1.2 on 2021-01-31 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210131_1745'),
    ]

    operations = [
    ]
