# Generated by Django 3.1.2 on 2021-01-31 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210131_1754'),
    ]

    operations = [
    ]
