# Generated by Django 3.1.2 on 2021-01-31 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_item_date'),
    ]

    operations = [

    ]
