# Generated by Django 3.1.2 on 2021-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210223_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='venue',
            field=models.CharField(choices=[('Scottish Event Campus', 'Scottish Event Campus'), ('King Tuts Wah Wah Hut', 'King Tuts Wah Wah Hut'), ('Barrowland Ballroom', 'Barrowland Ballroom'), ('Hampden Park', 'Hampden Park')], max_length=50),
        ),
    ]
