# Generated by Django 3.1.2 on 2021-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210223_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='venue',
            field=models.CharField(choices=[('O2 Academy', 'O2 Academy'), ('King Tuts', 'King Tuts'), ('Glasgow Green', 'Glasgow Green'), ('Hampden Park', 'Hampden Park')], max_length=50),
        ),
    ]
