# Generated by Django 3.1.2 on 2021-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='venue',
            field=models.CharField(choices=[('SECC', 'SECC'), ('Sub Club', 'Sub Club'), ('La Cheetah', 'La Cheetah')], max_length=10),
        ),
    ]
