# Generated by Django 3.1.2 on 2021-01-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
