# Generated by Django 3.1.2 on 2021-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_photo'),
    ]

    operations = [

    ]
