# Generated by Django 3.1.2 on 2021-01-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210131_1748'),
    ]

    operations = [

    ]
