# Generated by Django 3.1.2 on 2021-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210131_1756'),
    ]

    operations = [
    ]
