# Generated by Django 3.1.2 on 2021-01-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210131_1802'),
    ]

    operations = [

    ]
