# Generated by Django 3.1.2 on 2021-01-31 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
